swagger: "2.0"
info:
  description: This is the swagger file that goes with the server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"


# Paths supported by the server application
paths:
  /sorties:
    get:
      operationId: "sortie.read_all_sorties"
      tags:
        - "Sortie"
      summary: "The sortie data structure supported by the server application"
      description: "Read the list of sortie"
      responses:
        200:
          description: "Successful read sortie list operation"
          schema:
            type: array
            items:
              $ref: '#/definitions/Sortie'

  /user:
    post:
      operationId: user.create
      tags:
        - User
      summary: Create a user
      description: Create a new user
      parameters:
        - name: user
          in: body
          description: User to create
          required: True
          schema:
            type: object
            properties:
              firstName:
                type: string
                description: First name of person to create
              lastName:
                type: string
                description: Last name of person to create
      responses:
        201:
          description: Successfully created person
          schema:
            properties:
              firstName:
                type: string
                description: First name of the person
              lastName:
                type: string
                description: Last name of the person



definitions:
  Sortie:
    type: "object"
    properties:
      id_sortie:
        type: "integer"
      nom:
        type: "string"
      location:
        type: "string"
      date:
        type: "string"
      heure:
        type: "string"
      duree:
        type: "string"
      point_rdv:
        type: "string"
      capaciteMin:
        type: "integer"
      capacitemax:
        type: "integer"
      privee:
        type: "boolean"
      id_groupe:
        type: "integer"
      typeSortie:
        type: "string"
      photo:
        type: "string"
      nbInscrits:
        type: "integer"
      description:
        type: "string"
      dateLimite:
        type: "string"
      nom:
        commentaires: "string"